[tools]
# languages
python = ["3.11", "3.12"]
rust = "1.81.0"
terraform = "1.9.5"

# tools
uv = "0.4.9"
act = "latest"
actionlint = "latest"
hadolint = "latest"
1password-cli = "latest"
pre-commit = "latest"
bat = "latest"
eza = "latest"
ripgrep = "latest"
dust = "latest"
github-cli = "latest"
starship = "latest"
tflint = "latest"
tfsec = "latest"
gcloud = "latest"

# runtime
node = "22.8.0"